# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverID', models.CharField(max_length=64, unique=True)),
                ('serialNumber', models.CharField(max_length=64, unique=True)),
                ('serverName', models.CharField(max_length=16)),
                ('serverCore', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'Server',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=16, unique=True)),
                ('passWord', models.CharField(max_length=64)),
                ('upTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
