# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateField(verbose_name='日期')),
                ('m_time', models.TimeField(verbose_name='时间')),
                ('traffic', models.FloatField(verbose_name='流量')),
                ('diskname', models.CharField(max_length=128, verbose_name='云硬盘名称')),
            ],
            options={
                'db_table': 'Machine',
            },
        ),
    ]
